#!/usr/bin/env bash

# Install nginx
apt-get update
sudo apt install nginx-full -y

# Configure nginx
echo "Hello World!" > /var/www/html/index.html

# Start
systemctl start nginx
systemctl status nginx
