#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure custom header
sudo echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/nginx.conf > /dev/null

# Restart Nginx
sudo systemctl restart nginx

