#!/usr/bin/env bash
# Create file /var/run/myscript.pid containing it pid
# Disply "To infinity and beyond" indefinetly
# Disply "I hate the kill command" on SIGTERM
# Disply "Y U no love me?!" on SIGINT signal
# Deletes the pid file and terminates on SIGQUIT signal
trap "echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "exit" SIGQUIT

echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 10
done

